### ISSUE TITLE
The pretrained model for testing

### ISSUE THREAD

**Issue by Roxanne-Wang** [ga1i13o/Divide-and-Classify#1]
Could you please provide the pretrained model for testing? Thanks!

**Comment by ga1i13o** [comment]
Hi, thanks for the reminder. I have updated the README with a link to our main model, the Efficient-Net B0. will add more soon.
To use it you can copy the command from README, but you will need to have downloaded the dataset, and use the queries in `sf_xl_224/processed/test/queries_v1`
